### ISSUE TITLE
Badge rules

### ISSUE THREAD

**Issue by Nuranto** [RyanDaDeng/laravel-google-recaptcha-v3#1]
Is it somehow possible to manage badge display rules ?

For instance, would be great to display it inline, just next to the submit button instead of on every page, in a fixed position.

Of course there is a legal aspect, I'm not sure what we can do or not....

Some topics on this : 
https://stackoverflow.com/questions/53109566/how-do-i-hide-google-recaptcha-v3-from-my-site
https://stackoverflow.com/questions/50583284/how-do-you-set-the-badge-position-with-recaptcha-v3#answer-52557946

PS : You have an uncommented console.log() in your view.

**Comment by RyanDaDeng** [comment]
Hi, Nuranto, sorry for late reply. It's Xmas here, so I was a bit busy to clean up my company tasks. Anyway. Yeah, I will defintely look into your issues regarding the badge and also console.log(). I will make a patch tonight. Talk to you later.

**Comment by Nuranto** [comment]
Oh I do understand, same here.... it's crazy since Black Friday!
Thank you very much!
If I can help...

**Comment by RyanDaDeng** [comment]
Hello Nuranto, why not, you can help! You can create pull request or anything that I can help you set up.
By the way, according to Google official site, we are allowed to hide the badge, however, we still need to put some document or reference in user flow. e.g. Add a text line "This site is protected by Google blahblah...." in form. Please read the following link:

https://developers.google.com/recaptcha/docs/faq

section: "I'd like to hide the reCAPTCHA v3 badge"

**Comment by RyanDaDeng** [comment]
Hello Nuranto,

I might have solution to do that. link: https://developers.google.com/recaptcha/docs/invisible#js_api, just using Javascript API and render the badge into the form only. 

From your provided link's answer: https://jsfiddle.net/thatguysam/g7juvkdb/

**Comment by RyanDaDeng** [comment]
I think I have made it, let me update it soon.

**Comment by RyanDaDeng** [comment]
Hello Nuranto,

I have fully completed a new version, please upgrade your version.

Please also read new description in the home page.

The package now supports three badge display styles: inline, visible and global.

Additionally, you might need to re-publish the config file and also use new blade method to render. Please read the instructions on homepage.

Thank you for the feedback!

Merry Christmas!

**Comment by RyanDaDeng** [comment]
@Nuranto Can I close this ticket?

**Comment by RyanDaDeng** [comment]
@Nuranto any updates？

**Comment by Nuranto** [comment]
Hello @RyanDaDeng 
Sorry for the delay ! I just updated and test, it is perfect !

Thanks a lot !
