### ISSUE TITLE
Service provider doesn't support 5.4 version

### ISSUE THREAD

**Issue by NantipatSoftEn** [RyanDaDeng/laravel-google-recaptcha-v3#11]
My Laravel version 5.4 
When I add  providers and aliases at config/app.php 
I have error below this 
 
```
In GoogleReCaptchaV3ServiceProvider.php line 44:

  Call to undefined method Illuminate\Foundation\Application::has()
```

**Comment by RyanDaDeng** [comment]
@NantipatSoftEn Sorry about it, all test cases currently only covered source code except Service Provider, I might write test cases this weekend to cover the provider part.

Just updated the new version:  https://github.com/RyanDaDeng/laravel-google-recaptcha-v3/releases/tag/2.1.0

Please run the command below again, you should get your version updated:
`composer require timehunter/laravel-google-recaptcha-v3 "~2.0.0" -vvv`

Thank you for using the package, let me know if there are any issues. I will stay on the top of it.

**Comment by NantipatSoftEn** [comment]
> @NantipatSoftEn Sorry about it, all test cases currently only covered source code except Service Provider, I might write test cases this weekend to cover the provider part.
> 
> Just updated the new version: https://github.com/RyanDaDeng/laravel-google-recaptcha-v3/releases/tag/2.1.0
> 
> Please run the command below again, you should get your version updated:
> `composer require timehunter/laravel-google-recaptcha-v3 "~2.0.0" -vvv`
> 
> Thank you for using the package, let me know if there are any issues. I will stay on the top of it.

OK thx , I will try agin

**Comment by RyanDaDeng** [comment]
@NantipatSoftEn Hi, any good news?
