### ISSUE TITLE
README Error -  Wrong ValidationClass name

### ISSUE THREAD

**Issue by xalunda** [RyanDaDeng/laravel-google-recaptcha-v3#12]
Good morning!

Following the README process to use the Validation Class, I  arrived on a NotFound Exception.

#### REAME content:
```
use TimeHunter\LaravelGoogleReCaptchaV3\Validations\GoogleReCaptchaValidationRule;
$rule = [
    'g-recaptcha-response' => [new GoogleReCaptchaValidationRule('action_name')]
];
```

#### According to your code:
The class actually has `V3` in its name.
```
use TimeHunter\LaravelGoogleReCaptchaV3\Validations\GoogleReCaptchaV3ValidationRule;
$rule = [
    'g-recaptcha-response' => [new GoogleReCaptchaV3ValidationRule('action_name')]
];
```

This resolves the issue.

Thanks for this package.

**Comment by RyanDaDeng** [comment]
Good morning! @xalunda 
I have just updated the document, and also included it in the newest release already. https://github.com/RyanDaDeng/laravel-google-recaptcha-v3/releases/tag/2.1.0

Thank you very much!!

I am feeling motivated!

Best Regards

**Comment by xalunda** [comment]
You're very welcome Ryan :)

All works nice and smooth, thanks
