### ISSUE TITLE
An error occurs when using renderField()

### ISSUE THREAD

**Issue by kizashitakata** [RyanDaDeng/laravel-google-recaptcha-v3#33]
Thanks for the development.

When I use "renderField()" like this:
```
<form method="POST" action="/verify">
   {!!  GoogleReCaptchaV3::renderField('contact_us_id','contact_us_action') !!}
    <input type="submit" value="submit">
</form>
```
This error occurs.
`Type error: Too few arguments to function ` 

What this '$class' means?
`GoogleReCaptchaV3::renderField($id,$action,$class,$style)`
If my configuration is correct, will this '$class' be injected?

regards.

**Comment by kizashitakata** [comment]
Currently, I guess the HTML class attribute should be passed to "$ class". Correct?

**Comment by RyanDaDeng** [comment]
hello @kizashitakata , you are right. For some reasons, I missed the test cases. I will fix it now. Thank you so much.

**Comment by RyanDaDeng** [comment]
@kizashitakata Hello, I have fixed the error. That class is optional value which shouldn't be required. I fixed it with default empty string. Thank you for telling me about it! Thanks! I have added a test case. Please upgrade version to 2.2.12.

**Comment by kizashitakata** [comment]
Thank you for your prompt response!

**Comment by kizashitakata** [comment]
I confirmed the correction. Thank you very much. Please close the issue if it seems that there is no problem.

**Comment by RyanDaDeng** [comment]
thanks!
