### ISSUE TITLE
How to use refresh without vue.js?

### ISSUE THREAD

**Issue by Kolesar** [RyanDaDeng/laravel-google-recaptcha-v3#35]
I have simple modal dialog controlled with jquery. If Laravel validation return error, next submit does not work because ReCaptcha token is not refreshed. How can I run refresh token in this case?

**Comment by Kolesar** [comment]
I have found one temporary workaround, but a stupid one.

I removed `let` from `template.blade.php`

`client{{$field}} = grecaptcha.render('{{$field}}', {`

Create a "global" variable clientmy_field and on ajax failed response run:
```
                grecaptcha.reset(clientmy_field);
                grecaptcha.ready(function () {
                    grecaptcha.execute(clientmy_field, {
                        action: 'my_action'
                    });
                });
```

**Comment by RyanDaDeng** [comment]
@Kolesar Thanks for using the package! I will definitely take a look into this on Saturday.

**Comment by RyanDaDeng** [comment]
@Kolesar I encountered some problems. I cannot get recaptcha response (null) anymore after  grecaptcha.reset(widgetId).

do you have any ideas? 

`    <form>
        <div class="form-group">
            {!!  GoogleReCaptchaV3::renderField('contact_id','contact') !!}
            <button id="test" class="btn btn-success btn-submit">Submit</button>
        </div>
    </form>

    <script>
        $(document).ready(function () {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            
            $("#test").click(function (e) {
                e.preventDefault();
                $.ajax({
                    type: 'POST',
                    url: '/verify',
                    data: {'g-recaptcha-response':grecaptcha.getResponse(clientcontact_id)},
                    success: function (data) {
                        grecaptcha.reset(clientcontact_id);
                    }
                });
            });
        });
    </script>`

Note: I have made those client{{field}} as global variables in version 2.2.15.

**Comment by RyanDaDeng** [comment]
@Kolesar Thanks for the tips! I have updated the package and I have also added two handy javascript functions for Ajax usage. Please check document section - Blade Usage. Also please upgrade your version to be ~2.2.16

**Comment by RyanDaDeng** [comment]
@Kolesar any updates?

**Comment by Kolesar** [comment]
Hi @RyanDaDeng,

Sorry for the late response. I changed my business logic and have no problem with that at all. Thanks for the quick fix in any case. You can close this issue now.
