### ISSUE TITLE
Including on every pages throws ErrorException: Undefined variable: apiJsUrl

### ISSUE THREAD

**Issue by martsie** [RyanDaDeng/laravel-google-recaptcha-v3#36]
To reproduce simply put `{!!  GoogleReCaptchaV3::init() !!}` in the footer of your page layout with the default configuration (background mode on) and the site will crash.

This is happening because https://github.com/RyanDaDeng/laravel-google-recaptcha-v3/blob/master/src/GoogleReCaptchaV3.php#L67 which prepares the variables for the view does not contain apiJsUrl as a view variable which is required for the plugin to initialise.

**Comment by RyanDaDeng** [comment]
@martsie Hi, omg, this is critical and this is my bad. I merged this feature from one of contributors without thinking about the initialisation. I should have made some test cases to cover it. I have updated the code, please run update again, you should get version ~2.2.14

**Comment by martsie** [comment]
No worries, it happens - good to catch it early!
