### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by reefebba** [RyanDaDeng/laravel-google-recaptcha-v3#37]
Hello, I'm a newcomer, sorry to bother you with these stupid questions.

- do we add `is_score_enabled` again inside `setting => []` ? cause that what I see in readme but I think we already have, outside.

- I have `DesignRequest extends FormRequest `

and in rules() method I add

`'g-recaptcha-response' => ['required', new GoogleReCaptchaV3ValidationRule('submit_design')]` 

in controller I injected it.
in view:
```
<form action=design.store>
// other fields...
{!! GoogleReCaptchaV3::renderField('submit_design_id','submit_design') !!}
</form>
```
I have the badge appeared
because `{!!  GoogleReCaptchaV3::init() !!}`
and everything seems fine when I submitted a request.

but  I want to know if I've configured it right so I assign wrong value for my secret key but I got no error.
Any idea?

**Comment by RyanDaDeng** [comment]
1. do we add is_score_enabled again inside setting => [] ? cause that what I see in readme but I think we already have, outside.

You don't need to add it again in the setting => []. Yeah, I might need to re-wording it a bit to clear your confusion. 

2. For the wrong value,

Your config might be cached, you might need to run php artisan config cache or php artisan cache:clear

Let me know if it solves your problems.

**Comment by reefebba** [comment]
Thank you, now it won't submit the request, just like validation error but without any message. How do I get error messages and what would appear if suspicious user/bot submit a request?
Again, Thank You Very Much!

**Comment by RyanDaDeng** [comment]
> Thank you, now it won't submit the request, just like validation error but without any message. How do I get error messages and what would appear if suspicious user/bot submit a request?
> Again, Thank You Very Much!

You have to check the Facade Usage section to see the messages. However, I think the validation class has already returned some error messages. If you see nothing, it might be something wrong or something missing from my package, I will check it later tonight.

Check Facade Usage to see the returned object first. I will get back to you tonight.

**Comment by reefebba** [comment]
in my friend machine, he got a message that the site key isn't right when he didn't assign a value to it, Although I'm not sure why I don't even after `config:cache`, but I guess it works, which is great!!
Thank you for your attention and fast response

**Comment by RyanDaDeng** [comment]
thats good！
