### ISSUE TITLE
[Idea] Auto check on FormRequest resolve

### ISSUE THREAD

**Issue by thattomperson** [RyanDaDeng/laravel-google-recaptcha-v3#38]
just like how laravel will automatically validate a for rules on a FormRequest when it is resolved, it should be possible to do the same thing with Recaptcha with a interface and trait

```php
class MyRequest extends FormRequest implements RequiresRecaptcha {
    use HandlesRecaptcha

    protected $min_recaptcha_score = 0.3;
}
```

and then in the service provider 
```php
$this->app->afterResolving(RequiresRecaptcha::class, function ($resolved) {
    $resolved->handlesRecaptcha();
});
```

**Comment by RyanDaDeng** [comment]
@thattomperson 

I think this is a good idea honestly. This looks more OO and more practical. Let me have a try tonight or tmr.

Thanks! This is a really good idea.

**Comment by RyanDaDeng** [comment]
@thattomperson After research, I think it's better to include it into Validation class instead of form request. A bit busy last weekend, I will catch up with you later today.
