### ISSUE TITLE
Missing input response.

### ISSUE THREAD

**Issue by MwSpaceLLC** [RyanDaDeng/laravel-google-recaptcha-v3#40]
when i send call by blade, i have this problem. u know why ? 🤢

**Missing input response.**

Code Blade:
{!!  GoogleReCaptchaV3::render(['contact_us_id'=>'quote']) !!}

config:

    'setting' => [
        [
            'action' => 'quote',
            'threshold' => 0,
            'score_comparision' => false,
        ],
    ],

Controller:

        $this->request->validate([
            'g-recaptcha-response' => [new GoogleReCaptchaV3ValidationRule('quote')],
        ]);

**Comment by RyanDaDeng** [comment]
Have you put {!! GoogleReCaptchaV3::init() !!} at the bottom of your page?

**Comment by RyanDaDeng** [comment]
Also, have you added <div id="contact_us_id"></div> in your form?

**Comment by RyanDaDeng** [comment]
If you still had no success, I will take a look tonight. Bro, I am on your side.

**Comment by MwSpaceLLC** [comment]
No bro, sorry but for now i have installed : https://github.com/albertcht/invisible-recaptcha

🧐 I hope you can find the problem.

**Comment by RyanDaDeng** [comment]
> https://github.com/albertcht/invisible-recaptcha

Sure no worries. I will have a quick check tonight.

**Comment by akazemia** [comment]
I had the same issue until I noticed a hyphen "-" can lead to that issue.
Also don't forget to clean your cache:
php artisan cache:clear
php artisan config:cache
php artisan config:clear
php artisan cache:clear
php artisan view:clear
php artisan route:clear
composer dump-autoload
... I hope this helps someone out there ;)

**Comment by pouyaGit** [comment]
I just had the same problem...
I moved   {!! GoogleReCaptchaV3::init() !!}   from the script section of my blade to my master layout, 
and it was solved!

A bit weird but worked for me.
