### ISSUE TITLE
not reading published config file

### ISSUE THREAD

**Issue by henriquepalazzo** [RyanDaDeng/laravel-google-recaptcha-v3#41]
Hi,

for some reason, the copied config file is not being read. I spent a long time trying to find what I was doing wrong, without any success. I was getting an error message on the console saying: missing site key. So I put the site key string directly on the config file inside the vendor folder, since then I didn't get the error message anymore. Am I doing something wrong or there is indeed a bug?

Thanks.

**Comment by RyanDaDeng** [comment]
Have you tried `php artisan config:cache`?

**Comment by RyanDaDeng** [comment]
If you still had no success, I will take a look tonight. We will sort it out.

**Comment by henriquepalazzo** [comment]
Hi RyanDaDeng, I tried, no success. Any ideia?

**Comment by RyanDaDeng** [comment]
@henriquepalazzo I tried to install a fresh package on a new project, it doesn't have issues for me. 

my laravel version: 5.8

1.  run publish to have a config in your local
2. adding secret and site key
3. Adding two routes:
    `  Route::get('echo', 'EchoController@echo');
        Route::post('echo2', 'EchoController@echo2');`
4. Adding blade:
    `<form method="POST" action="/api/echo2">
                    @csrf
                    {!!  GoogleReCaptchaV3::renderField('contact_us_id','contact_us_action') !!}
                    <input type="submit" value="submit">
                </form>
    {!!  GoogleReCaptchaV3::init() !!}`
5. Create a controller:
`class EchoController extends Controller
{
    public function echo(Request $request)
    {
        return view('welcome');
    }

    public function echo2(Request $request)
    {
        dd(GoogleReCaptchaV3::verifyResponse($request->input('g-recaptcha-response')));
    }
}`

**Comment by RyanDaDeng** [comment]
The problem in your case is that the config file is not being picked up. It's usually caused by cache issues. What's the Laravel version are you using at the moment?
