### ISSUE TITLE
add multiple recaptcha

### ISSUE THREAD

**Issue by themall7** [RyanDaDeng/laravel-google-recaptcha-v3#47]
I have two popups on same page and both have their own recaptcha but there is an error on console. it says "reCAPTCHA has already been rendered in this element".
Can I use multiple recaptcha in single page?
Laravel : 5.5.46
Vue : 2.6.10

**Comment by RyanDaDeng** [comment]
@themall7 Have you tried to set up different *ref* and *v-model* for vue component?

                <google-re-captcha-v3
                        ref="captcha"   // set it differently
                       v-model="gRecaptchaResponse" // set it differently
                        :siteKey="'Your Site Key Here'"
                        :id="'contact_us_id'"
                        :inline="true"
                        :action="'contact_us'">
                </google-re-captcha-v3>

**Comment by themall7** [comment]
I tried but no luck. same error have occurred.

recaptcha__ko.js:545 Uncaught Error: reCAPTCHA has already been rendered in this element
    at Object.Yp [as render] (recaptcha__ko.js:545)
    at VueComponent.render (app.js:107144)
    at window.gRecaptchaOnLoad (app.js:107125)
    at Rn (recaptcha__ko.js:555)
    at w3 (recaptcha__ko.js:553)
    at recaptcha__ko.js:559
    at recaptcha__ko.js:579

**Comment by RyanDaDeng** [comment]
I might investigate it tmr. Don’t worry I will fix it up if it’s the bug.

**Comment by themall7** [comment]
Hi,
Any progress for this case?
Thanks.

**Comment by xalunda** [comment]
Wooo I've been assigned an old issue there ^^"

@themall7 Is the issue resolved on your end?
If not, could you make a codepen or attach the content of your file `recaptcha__ko.js` ?

_ko? Are you using KnockoutJS ?

Thanks

**Comment by RyanDaDeng** [comment]
@xalunda omg, I just assign it randomly to you. I didn't expect you would fix it...omg, THANKS, you are the legend.. I am moving house and purchasing a property so busy this year. Sorry for the inconvenience.

**Comment by xalunda** [comment]
That's fine, I'm using this package in production so I have interests in keeping it updated 👍 

I hope this person found what was wrong with his code, he/she has been waiting a long time
