### ISSUE TITLE
Move site key and secret key to environment file

### ISSUE THREAD

**Issue by NoxxieNl** [RyanDaDeng/laravel-google-recaptcha-v3#48]
Hiya,

First thanks for this package love it to use in combination with the automatic validation check within a controller :-)!

Perhaps it would be nice if we could set the `secret key` and the `site key` inside our environment file. Sometimes you do not want those keys to be up in your repository. as simple change in the config file would to do this.

Want to send a PR when it's OK :-)

**Comment by RyanDaDeng** [comment]
@NoxxieNl thanks! I have added it in .env! Let me know if the current version satisfy your requirement.

**Comment by NoxxieNl** [comment]
That does the trick! :)
Thanks!
