### ISSUE TITLE
rendering issues

### ISSUE THREAD

**Issue by KaminoU** [RyanDaDeng/laravel-google-recaptcha-v3#55]
Hello,

First of all thank you for the package.

Maybe I did wrong but the init() method does not render correctly : 
• it does not render the reCaptcha V3 Api.js
• all the action name is merged with the string '-contact'

My laravel version is **6.2** and this is what I do by following your documentation.

**My Blade File, before the /body** : 
`{!!  GoogleReCaptchaV3::init() !!}`

**in the $.ajax()** : 
my data to send `data:$.extend($(this), {'g-recaptcha-response': getReCaptchaV3Response('id_div_inline_recaptcha_badge')}).serialize()`

**in my success/error calback** : 
`refreshReCaptchaV3('id_div_inline_recaptcha_badge', 'visitor-contact');`

**my form** : 
`    @csrf
    {{-- inputs... --}}
    {!!  GoogleReCaptchaV3::renderField('id_div_inline_recaptcha_badge', 'visitor-contact') !!}`

I check the log and and network console, no errors raised, but there is no google api.js and all my action have the '-contact' appended (so in this case, my action becomes 'visitor-contact-contact')

Thank you for reading

**Comment by RyanDaDeng** [comment]
I will check it during this weekend. Thank you for using the package.

**Comment by KaminoU** [comment]
Thanks for reading ^^

I finally made my own class and it works like a charm. It seems that some packages do not work correctly on Laravel 6.x (without errors)

**Comment by RyanDaDeng** [comment]
@KaminoU Hello, I have tested myself by using a fresh new Laravel 6.x project.

I have no issues on using the package.

**Blade file:**

`<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <title>Test</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <meta name="csrf-token" content="{{ csrf_token() }}" />
    <script type="text/javascript">
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
    </script>
</head>
<body>

<div>
    Normal Form
    <form method="POST" action="/verify">
        @csrf
        {!!  GoogleReCaptchaV3::renderField('contact_us_id','contact_us_action') !!}
        <input type="submit" value="submit">
    </form>
</div>

<hr>
Ajax Form
<form method="POST" action="/verify">
    @csrf
    {!!  GoogleReCaptchaV3::renderField('contact_us_ajax_id','contact_us_action') !!}
    <button id="test">Submit</button>
</form>
</div>
</body>

<script>
    $("#test").click(function (e) {
        console.log('11');
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '/verify',
            data: {
                'g-recaptcha-response': getReCaptchaV3Response('contact_us_ajax_id')
            },
            success: function (data) {
                refreshReCaptchaV3('contact_us_ajax_id', 'contact_us_action');
            },
            error: function (err) {
                refreshReCaptchaV3('contact_us_ajax_id', 'contact_us_action');
            }
        });
    });
</script>

{!!  GoogleReCaptchaV3::init() !!}
</html>
`

**route file**

`use TimeHunter\LaravelGoogleReCaptchaV3\Validations\GoogleReCaptchaV3ValidationRule;
Route::get('/', function (\Illuminate\Http\Request $request) {
    return view('welcome');
});


Route::post('/verify', function (\Illuminate\Http\Request $request) {

    $rule = [
        'g-recaptcha-response' => [new GoogleReCaptchaV3ValidationRule('contact_us_action')]
    ];

    $validator = \Illuminate\Support\Facades\Validator::make($request->toArray(),$rule)->errors();

    dd($validator->toArray());
});`

**Comment by KaminoU** [comment]
Thank you @RyanDaDeng 

I will give a try again then ; it seems that I did wrong while implementing your package =D

**Comment by KaminoU** [comment]
Sorry misspelling lol =D
