### ISSUE TITLE
Multi Language Suuport not working for background_mode 

### ISSUE THREAD

**Issue by stzoran1** [RyanDaDeng/laravel-google-recaptcha-v3#57]
I spotted that custom language is not working for background_mode = true. No matter which language is set it will always load badge in English.

**Comment by RyanDaDeng** [comment]
@stzoran1 I might knew why. I will have a look by this week. Thanks!

**Comment by RyanDaDeng** [comment]
@stzoran1 this is fixed. sorry about waiting for this long.
