### ISSUE TITLE
/verify route not being registered

### ISSUE THREAD

**Issue by tongtastic** [RyanDaDeng/laravel-google-recaptcha-v3#58]
After completing the installation instructions, any request, regardless of type, made to /verify results in a 404.

No cache, all cleared, running using VueJS validation
Laravel 6.5.2

Thanks in advance

**Comment by abishekrsrikaanth** [comment]
Got the same issue. @RyanDaDeng any idea how to fix this?

**Comment by RyanDaDeng** [comment]
im looking into it

**Comment by RyanDaDeng** [comment]
@tongtastic @abishekrsrikaanth `/verify` should be implemented by your end. It is just a example route in the demo. You need to specify your own controller function and receive response and then check https://github.com/RyanDaDeng/laravel-google-recaptcha-v3#validation-class Validation Usage

**Comment by RyanDaDeng** [comment]
or check this sample: https://github.com/RyanDaDeng/laravel-google-recaptcha-v3/wiki/Simple-Demo
