### ISSUE TITLE
Getting timeout error

### ISSUE THREAD

**Issue by samuelhgf** [RyanDaDeng/laravel-google-recaptcha-v3#59]
I'm using recpatcha in Vue. I call this method: this.$refs.captcha.execute(); after the user login success or erro and after logout. Anytime I call it returns this two errors:

recaptcha__pt_br.js:500 Timeout (n)
Uncaught (in promise) Timeout (n)

Even so the token works in the authentication every time the user log in. In the first place or after logout without refresh the page.

**Comment by RyanDaDeng** [comment]
I will check it these days. thanks!!

**Comment by samuelhgf** [comment]
Hi, any news?

**Comment by Dissociable** [comment]
@samuelhgf Do this to fix it:

> GoogleReCaptchaV3.vue

Add this method:
`renderCallBack(data) {},`

then add this parameter to grecaptcha.render function:
`'callback': this.renderCallBack,`

It will look like this:
```
render() {
            this.captchaId = window.grecaptcha.render(this.id, {
                sitekey: this.siteKey,
                badge: this.inline === true ? 'inline' : '',
                size: 'invisible',
                'callback': this.renderedCallBack,
                'expired-callback': this.execute
            });

            this.execute();
        },

        renderedCallBack(data) {},
```

And also if you doing tests in localhost, add the domains in Recaptcha's Admin Console
```
localhost
127.0.0.1
```

**Comment by Dissociable** [comment]
Hello, to prevent session timeouts of Recaptcha Validation and the need of reloading page, i call the execute method on the button click of the forms, of course i made some changes to the Vue component,

```
    render() {
        this.$emit('input', null);
        this.captchaId = window.grecaptcha.render(this.id, {
            sitekey: this.siteKey,
            badge: this.inline === true ? 'inline' : '',
            size: 'invisible',
            'callback': this.renderedCallBack,
            'error-callback': this.errorCallBack,
            'expired-callback': this.expCallback
        });
    },

    renderedCallBack(data) {},

    errorCallBack(data) {},

    expCallback: function() {},

    execute() {
        return new Promise((resolve, reject) => {
            if (window.grecaptcha) {
                window.grecaptcha.execute(this.captchaId, {
                    action: this.action,
                }).then((token) => {
                    this.$emit('input', token);
                    resolve(token);
                });
            };
        });
    }
```

```
<google-re-captcha-v3 v-model="form.gRecaptchaResponse" ref="captchasubmitticket" id="submitticket_id" :inline="true" action="submitticket" />
```
The above v-model is not needed as you can get the token like this:
```
this.$refs.captchasubmitticket.execute().then((token) => {
    console.log(token);
});
```
