### ISSUE TITLE
Content Security Policy - Add Nonce

### ISSUE THREAD

**Issue by lxlang** [RyanDaDeng/laravel-google-recaptcha-v3#62]
At the moment it is very hard to get this working on a implemented Content-Security-Policy. 

It would be great if we could pass a nonce to the generated script tags in `init()`. 

There is already a fork by @Weisskpub containing this: https://github.com/Weisskpub/laravel-google-recaptcha-v3

I personally like this approach, but its your project and the decision how its implemented is yours. 

Thanks for this great package!

**Comment by RyanDaDeng** [comment]
@lxlang hey thanks! I will check @Weisskpub repo to see how it works. Thanks! I will try to update it within this week.

**Comment by RyanDaDeng** [comment]
@lxlang hi, sorry for the delay. I got some urgent company tasks to do this weekend. I might not have time this weekend. just a quick update.

**Comment by lxlang** [comment]
@RyanDaDeng Thanks alot :)
