### ISSUE TITLE
Laravel 8.0 release not installable

### ISSUE THREAD

**Issue by Schnoop** [RyanDaDeng/laravel-google-recaptcha-v3#72]
As php-coveralls is currently not supporting Guzzle 7.0, which is a requirement for Laravel 8.0, this package is not installable at the moment.
https://github.com/php-coveralls/php-coveralls/issues/287

**Comment by RyanDaDeng** [comment]
Will fix it as high priority by this weekend! Thanks!

**Comment by RyanDaDeng** [comment]
hello @Schnoop  this is fixed. Actually, the package doesn't require guzzle as dependencies for itself.

All good now.

**Comment by Schnoop** [comment]
Great news. Thanks a lot for your work!
