### ISSUE TITLE
Struggling to implement on registration

### ISSUE THREAD

**Issue by russ-sdg** [RyanDaDeng/laravel-google-recaptcha-v3#74]
I'm guessing this is user error as I'm relatively new to Laravel. I am trying to use Recaptcha v3 on the standard registration form that comes with Laravel. 

In the config file I have:
    'setting' => [
        [
            'action' => 'login',
            'threshold' => 0.5,
            'inline' => true,
            'score_comparision' => false,
        ],
        [
            'action' => 'registration',
            'threshold' => 0.5,
            'inline' => true,
            'score_comparison' => false,
        ],
    ],

In the blade I have all the normal fields plus:
                    <form method="POST" action="{{ route('register') }}" id='register-form'>
                        @csrf
...
                                <div id="registration_id"></div>
                                <button class="btn btn-primary">
                                    {{ __('Register') }}
                                </button>
...
{!! GoogleReCaptchaV3::render([
    'registration_id'=>'registration'
  ]) !!}

In the controller I have:
    protected function validator(array $data)
    {
        return Validator::make($data, [
            'g-recaptcha-response' => [new GoogleReCaptchaV3ValidationRule('registration')],
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
            'password' => ['required', 'string', 'min:8', 'confirmed'],
        ]);
    }

What am I missing?
Thanks!

**Comment by ljanecek** [comment]
You should add `{!! GoogleReCaptchaV3::init() !!}` into layout template, app.blade.php to the bottom.

**Comment by russ-sdg** [comment]
That did it. Thank you!

**Comment by RyanDaDeng** [comment]
better to check this sample code: https://github.com/RyanDaDeng/laravel-google-recaptcha-v3/wiki/Simple-Demo
