### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by asmxaker** [RyanDaDeng/laravel-google-recaptcha-v3#86]
If I use Laravel HTMLMin 

```Uncaught SyntaxError: Unexpected end of input```

`   var clientcontact_us_id;   function onloadCallback() {   if (document.getElementById('contact_us_id')) { clientcontact_us_id = grecaptcha.render('contact_us_action', { 'sitekey': '123',  'size': 'invisible', 'hl': 'ru', //'callback': function() {} }); grecaptcha.ready(function () { grecaptcha.execute(clientcontact_us_id, { action: 'contacts' }); }); }   } `

comment   //'callback': function() 
breaks the closing js statement 

or change comment to /**/ or delete callback

**Comment by RyanDaDeng** [comment]
its a bit weird not throwing errors before, i have just deleted it.

let me know if it works now.

v2.5.1

**Comment by asmxaker** [comment]
everything is wonderful!
